# Generated by Django 5.1.3 on 2024-11-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="hashtag",
        ),
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(to="content.hashtag"),
        ),
    ]
