# Generated by Django 5.1.3 on 2024-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_post_hashtag_post_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(related_name="posts", to="content.hashtag"),
        ),
    ]
