# Generated by Django 5.1.3 on 2024-11-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_post_hashtag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="content.hashtag"
            ),
        ),
    ]
