# Generated by Django 5.1.3 on 2024-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_post_options_alter_post_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=63),
        ),
    ]
