# Generated by Django 5.1.3 on 2024-11-28 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_hashtag_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="postreaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="postreaction",
            unique_together={("user", "post")},
        ),
    ]
